In [2]:
import os
import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import img_to_array

In [3]:
#Load the Model
def get_model():
    global model
    model = load_model('model.h5')
    print("Model loaded!")

In [4]:
get_model()

Model loaded!


In [5]:
# Define the image attributes, including path and size
def load_image(img_path):

    img = image.load_img(img_path, target_size=(224, 224))
    img_tensor = image.img_to_array(img)
    img_tensor = np.expand_dims(img_tensor, axis=0)         
    img_tensor /= 255.                                     

    return img_tensor

In [6]:
# Define the prediction model, and the prediction logic
def prediction(img_path):
    new_image = load_image(img_path)
    
    pred = model.predict(new_image)
    
    print(pred)
    
    labels=np.array(pred)
    labels[labels>=0.6]=1
    labels[labels<0.6]=0
    
    print(labels)
    final=np.array(labels)
    
    if final[0][0]==1:
        return "Bad"
    else:
        return "Good"

In [13]:
# Test1
prediction(r'C:/Users/dhrupad/Desktop/EGEE-529/Project/Dataset/test/test1/bad (75)k.jpeg')

1/1 [==============================] - 0s 34ms/step
[[0.9979213  0.00207879]]
[[1. 0.]]


'Bad'

In [9]:
# Test2
print(prediction(r'C:/Users/dhrupad/Desktop/EGEE-529/Project/Dataset/test/test1/good (361)k.jpeg'))

1/1 [==============================] - 0s 34ms/step
[[1.0334545e-04 9.9989665e-01]]
[[0. 1.]]
Good


In [11]:
# Test3
product = prediction(r'C:/Users/dhrupad/Desktop/EGEE-529/Project/Dataset/test/test1/bad (25)k.jpeg')  

1/1 [==============================] - 0s 34ms/step
[[9.9996936e-01 3.0587224e-05]]
[[1. 0.]]


In [12]:
product

'Bad'